# Generated by cucumber-sinatra. (2014-05-10 12:21:25 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'

Capybara.app = Chitter

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end

DatabaseCleaner.strategy = :truncation

Before do
	DatabaseCleaner.start
end

After do
	DatabaseCleaner.clean
end
